### ISSUE TITLE
Action seems broken with Camel K 2.0

### ISSUE THREAD

**Issue by christophd** [container-tools/camel-k-action#3]
Using the action with latest version is failing with this error:

```
Run container-tools/camel-k-action@v1
  with:
  env:
    YAKS_IMAGE_NAME: kind-registry:5000/yaks
    YAKS_IMAGE_VERSION: latest
    YAKS_RUN_OPTIONS: --timeout=180s
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.[2](https://github.com/citrusframework/yaks/actions/runs/5858655067/job/15883037734#step:9:2)0-8/x6[4](https://github.com/citrusframework/yaks/actions/runs/5858655067/job/15883037734#step:9:4)
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.20-8/x64
    GOROOT: /opt/hostedtoolcache/go/1.18.10/x64
    KIND_REGISTRY: kind-registry:[5](https://github.com/citrusframework/yaks/actions/runs/5858655067/job/15883037734#step:9:5)000
Installing Camel K CLI version latest=v2.0.0 on linux...

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
